config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'

  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true,
                    length: {minimum: 7}
  has_many  :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :get_article, only: [:edit, :update, :destroy, :show]
  def index
    @articles = Article.all
  end

  def create
    @article = Article.new(article_params)


    if @article.save
      redirect_to article_path(@article.id)
    else
      render 'new'
    end
  end

  def edit

  end

  def show

    @comment = @article.comments.new
    @comments = @article.comments.all
  end

  def new
    @article = Article.new
  end

  def update



    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end

  end

  def destroy
  @article.destroy
  redirect_to articles_path
  end


  private
  def get_article
    @article = Article.find(params[:id])
  end
  def article_params
   params.require(:article).permit(:title, :text, :checkbox)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_article
  before_action :get_comment, only: [:destroy, :update, :show, :edit]
  def index

    @comments = @article.comments.all
  end

  def new

    @comment = @article.comments.new
  end

  def edit


  end

  def show


  end

  def update



    if @comment.update(comment_params)
      redirect_to [@article, @comment]
    else
      render "edit"
    end
  end

  def destroy


    @comment.destroy
    redirect_to @article
  end

  def create

   @comment = @article.comments.new(comment_params)

   if @comment.save
    #redirect_to @article
    respond_to do |format|
      format.json {render json: @comment, status: 201}
    end
   else
     render "new"
   end

  end



  private
  def get_article
        @article = Article.find(params[:article_id])
  end
  def get_comment
        @comment = @article.comments.find(params[:id])
  end
  def comment_params
    params.require(:comment).permit(:commentor, :body, :article_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for article do |f| %>
<% if article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<p>
<%= f.label :title %></br>
<%= f.text_field :title %>
</p>
<p>
<%= f.label :text %>
<%= f.text_area :text%>
</p>
<p>
<%= f.label :checkbox %>
<%= f.check_box :checkbox%>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/articles/edit.html.erb
<%= render "form", article: @article%>

app/views/articles/index.html.erb
<h1>Articles</h1>
<%= link_to "new", new_article_path %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th>Checkbox</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |a| %>
    <tr>
      <td><%= a.title %></td>
      <td><%= a.text %> </td>
      <td><%= a.checkbox %> </td>
      <td><%= link_to "show", article_path(a)  %> </td>
      <td><%= link_to "edit", edit_article_path(a)  %> </td>
      <td><%= link_to "delete", article_path(a), method: :delete, data: {confirm: "ARE YOU SURE?"}  %> </td>



    </tr>
    <%end%>
</tbody>
</table>

app/views/articles/new.html.erb
<%= render "form", article: @article%>

app/views/articles/show.html.erb
<p>
  <strong>Title</strong></br>
  <%= @article.title %>
</p>
<p>
<strong>Text</strong></br>
<%= @article.text %>
</p>
<p>
<strong>Checkbox</strong></br>
<%= @article.checkbox %>
</p>


<button id="comment_button" type="button">COMMENT?</button>
<%#= render "comments/form", comment: [@article, @comment] %>



<form id="form_two" data-article-id="<%= @article.id %>">
  Commentor:<br>
  <input id="html_form_commentor" type="text" name="commentor">
  <br>
  Body:<br>
  <input id="html_form_body" type="text" name="body">
  Checkbox:<br>
  <br><br>
  <input id="html_form_checkbox" type="checkbox" name="checkbox">
  <br><br>

  <button class="save" type="button">SAVE</button>

</form>
<button id="comments_table_button" type="button">READ COMMENT?</button>
<table id="comments_table">
  <thead>
    <tr>
      <th>Commentor</th>
      <th>Body</th>
      <th>article</th>
    </tr>
  </thead>
  <tbody>
<%= render  @comments %>
</tbody>
</table>

<%= link_to "edit", edit_article_path(@article) %>
<%= link_to "index", articles_path %>
<%= link_to "sign_out", destroy_user_session_path, method: :delete, data: {confirm: "ARE YOU SURE?"}  %>

app/views/comments/_comment.html.erb
    <tr>
      <td><%= comment.commentor %></td>
      <td><%= comment.body %></td>
      <td> <span class="fidelity" data-truth-id="<%= comment.id %>"><%= comment.article_id %></span></td>
      <td><%= link_to "show", article_comment_path(comment.article, comment) %></td>
      <td><%= link_to "edit", edit_article_comment_path(comment.article, comment) %></td>
      <td><%= link_to "delete", article_comment_path(comment.article, comment), method: :delete, data: {confirm: "ARE YOU SURE?"} %></td>


    </tr>

app/views/comments/_form.html.erb
<%= form_for comment do |f|%>

<p>
<%= f.label :commentor%></br>
<%= f.text_field :commentor%>
</p>
<p>
<%= f.label :body%></br>
<%= f.text_field :body%>
</p>
<p>
<!-- <%= f.label :article%></br>
<%= f.collection_select(:article, Article.all, :id, :title)%>
</p> -->

<p>
<%= f.submit %>
</p>
<% end %>

app/views/comments/edit.html.erb
<%= render "form", comment: [@article, @comment]%>

app/views/comments/index.html.erb
<table>
  <thead>
    <tr>
      <th>Commentor</th>
      <th>Body</th>
      <th>article</th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |c|%>
    <tr>
      <td><%= c.commentor %><td>
      <td><%= c.body %><td>
      <td><%= c.article_id %><td>
      <td><%= link_to "show", article_comment_path(@article, c) %><td>
      <td><%= link_to "edit", edit_article_comment_path(@article, c) %><td>
      <td><%= link_to "delete", article_comment_path(@article, c), method: :delete, data: {confirm: "ARE YOU SURE?"} %><td>


    </tr>
    <% end %>
  </tbody>
</table>

app/views/comments/new.html.erb
<%= render "form", comment: [@article, @comment]%>

app/views/comments/show.html.erb
<strong> commentor </strong>
<%= @comment.commentor%>
<strong> body </strong>
<%= @comment.body%>
<strong> article </strong>
<%= @comment.article_id%>

<%= link_to "edit", edit_article_comment_path(@article, @comment) %>
<%= link_to "index", article_comments_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>